#13: Adding Contributing.md file
PortoTestersMeetup/portotestersmeetup.github.io pull request #14
Opened 2017-10-09 16:42 UTC by filipemcarvalho

Looking to resolve #13

2017-10-09 18:18 UTC, filfreire requested changes
There is an easier way to link to contributing file from readme:
```
[CONTRIBUTING.md](CONTRIBUTING.md)
```
instead of full link
```
https://github.com/PortoTestersMeetup/portotestersmeetup.github.io/blob/master/CONTRIBUTING.md
```
edit: @filipemcarvalho @FabioCB  FYI

2017-10-09 21:29 UTC, filfreire approved these changes

2017-10-10 16:44 UTC, FabioCB requested changes

2017-10-10 16:44 UTC, FabioCB commented on CONTRIBUTING.md
> +If you want to contribute to a project and make it better, your help is very welcome.
Add a Title to the Page

2017-10-10 16:44 UTC, FabioCB commented on README.md
> +# How to use your github repository to test
Why not move this to contributing file?

2017-10-10 16:59 UTC, filipemcarvalho commented on CONTRIBUTING.md
> +If you want to contribute to a project and make it better, your help is very welcome.
Done

2017-10-10 16:59 UTC, filipemcarvalho commented on README.md
> +# How to use your github repository to test
Done

2017-10-10 17:01 UTC, FabioCB approved these changes

2017-10-10 17:02 UTC, merged