Wording improvements
PortoTestersMeetup/portotestersmeetup.github.io pull request #16
Opened 2017-10-10 17:19 UTC by filipemcarvalho

2017-10-11 09:37 UTC, FabioCB requested changes

2017-10-11 09:37 UTC, FabioCB commented on README.md
> +3. Select **New issue**
capital letter I on Issues

2017-10-11 10:37 UTC, filfreire commented on README.md
> +3. Select **New issue**
Maybe on `tab`, capital letter T too no?

2017-10-11 17:09 UTC, filipemcarvalho commented on README.md
> +3. Select **New issue**
Done 👍

2017-10-12 07:03 UTC, filfreire approved these changes

2017-10-12 08:56 UTC, FabioCB approved these changes

2017-10-12 08:56 UTC, merged