Added home button to cfv.md and cfv.md files
PortoTestersMeetup/portotestersmeetup.github.io pull request #26
Opened 2017-11-03 00:01 UTC by AugustasV

Maybe could be problems with link, we will see. It should work!

2017-11-03 08:01 UTC, filfreire requested changes
@AugustasV thank you for your contribution 👍 
Please take a look at the other comment I wrote.

2017-11-03 08:01 UTC, filfreire commented on pages/cfs.md
> +<html>
@AugustasV i believe the `<html>...</html>` aren't required here, you can just keep the center and the the button web elements.

2017-11-03 09:22 UTC, filipemcarvalho commented on pages/cfs.md
> + <center><a href=".../index.html"><button type="button">Home</button></a></center>
Shouldn't this be '../index.html' instead of '.../index.html' ?

2017-11-03 09:22 UTC, filipemcarvalho commented on pages/cfv.md
> + <center><a href=".../index.html"><button type="button">Home</button></a></center>
Same as above

2017-11-03 10:33 UTC, AugustasV reviewed
Updated files according feedback you gave .

2017-11-06 10:00 UTC, filipemcarvalho approved these changes

2017-11-06 14:12 UTC, merged